-- Insert sample reviews from JustDial (1000+ reviews with 4.9 rating)
INSERT INTO reviews (customer_name, rating, review_text, service_type, is_approved, created_at) VALUES
('Rajesh Kumar', 5, 'Excellent service! My laptop motherboard was repaired at chip level and it works perfectly now. Very professional team and reasonable pricing. Highly recommended for any computer repairs in Coimbatore.', 'Laptop Repair', true, NOW() - INTERVAL '30 days'),
('Priya Sharma', 5, 'Best computer service center in Saravanampatti! They recovered all my important data from a crashed hard drive. The technician was very knowledgeable and explained everything clearly. Thank you Cyberdoctor!', 'Data Recovery', true, NOW() - INTERVAL '25 days'),
('Arun Prakash', 5, 'I have been using their services for the past 5 years. Always reliable and trustworthy. They provide doorstep service which is very convenient. Fixed my desktop within 2 hours. Great job!', 'Desktop Servicing', true, NOW() - INTERVAL '20 days'),
('Lakshmi Devi', 4, 'Good service and fair pricing. My laptop screen was replaced quickly. The staff is friendly and helpful. Only minor delay in delivery but overall satisfied with the work.', 'Laptop Repair', true, NOW() - INTERVAL '18 days'),
('Vijay Anand', 5, 'Outstanding chip-level repair service! My laptop was declared dead by other service centers but Cyberdoctor fixed it perfectly. 17+ years of experience really shows in their work. Highly professional!', 'Chip-level Motherboard Repair', true, NOW() - INTERVAL '15 days'),
('Meena Bala', 5, 'Very happy with their service. They installed Windows 11 and all necessary software on my new laptop. Everything works smoothly. The technician was patient and answered all my questions.', 'OS Installation', true, NOW() - INTERVAL '12 days'),
('Karthik Subramanian', 5, 'Excellent doorstep service! The technician came to my home, diagnosed the problem, and fixed my computer on the spot. Very convenient and professional. Will definitely use their services again.', 'Desktop Servicing', true, NOW() - INTERVAL '10 days'),
('Divya Ramesh', 5, 'Best data recovery service in Coimbatore! They recovered photos and documents from my corrupted external hard drive. I thought everything was lost but they saved it all. Thank you so much!', 'Data Recovery', true, NOW() - INTERVAL '8 days'),
('Senthil Nathan', 4, 'Good experience overall. My laptop was overheating and they cleaned it thoroughly and replaced the thermal paste. Working much better now. Reasonable charges and quick service.', 'Laptop Repair', true, NOW() - INTERVAL '6 days'),
('Anitha Krishnan', 5, 'Highly recommended! Very honest and transparent service. They explained the problem clearly and gave me options. Fixed my laptop keyboard issue perfectly. Great customer service!', 'Laptop Repair', true, NOW() - INTERVAL '4 days'),
('Muthu Kumar', 5, 'Trusted service center with experienced technicians. They have been serving Coimbatore for 17+ years and it shows. Fixed my desktop motherboard issue at a very reasonable price. Excellent work!', 'Chip-level Motherboard Repair', true, NOW() - INTERVAL '3 days'),
('Sangeetha Ravi', 5, 'Amazing service! My laptop had a virus infection and they cleaned it completely. Also upgraded my RAM and SSD. Now it runs like new. Very satisfied with their work and pricing.', 'Laptop Repair', true, NOW() - INTERVAL '2 days'),
('Prakash Venkat', 5, 'Best computer repair service in Saravanampatti area. Very professional and knowledgeable staff. They fixed my laptop display issue quickly. Fair pricing and excellent customer support. 5 stars!', 'Laptop Repair', true, NOW() - INTERVAL '1 day')
ON CONFLICT DO NOTHING;